#!/usr/bin/env python3
import sys
import os

for root, dirs, files in os.walk(sys.argv[2]) :
    for i in files :
        if i.endswith(("txt","yml","yaml")):
            with open(os.path.join(root, i), 'r', encoding="UTF-8") as file:
                for num, line in enumerate(file, 1):
                    if sys.argv[1] in line:
                        print(os.path.join(root, i), ": ", str(num), ": ",line)
